require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BankrollsController do

  # This should return the minimal set of attributes required to create a valid
  # Bankroll. As you add validations to Bankroll, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "purchase" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BankrollsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all bankrolls as @bankrolls" do
      bankroll = Bankroll.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bankrolls).should eq([bankroll])
    end
  end

  describe "GET show" do
    it "assigns the requested bankroll as @bankroll" do
      bankroll = Bankroll.create! valid_attributes
      get :show, {:id => bankroll.to_param}, valid_session
      assigns(:bankroll).should eq(bankroll)
    end
  end

  describe "GET new" do
    it "assigns a new bankroll as @bankroll" do
      get :new, {}, valid_session
      assigns(:bankroll).should be_a_new(Bankroll)
    end
  end

  describe "GET edit" do
    it "assigns the requested bankroll as @bankroll" do
      bankroll = Bankroll.create! valid_attributes
      get :edit, {:id => bankroll.to_param}, valid_session
      assigns(:bankroll).should eq(bankroll)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bankroll" do
        expect {
          post :create, {:bankroll => valid_attributes}, valid_session
        }.to change(Bankroll, :count).by(1)
      end

      it "assigns a newly created bankroll as @bankroll" do
        post :create, {:bankroll => valid_attributes}, valid_session
        assigns(:bankroll).should be_a(Bankroll)
        assigns(:bankroll).should be_persisted
      end

      it "redirects to the created bankroll" do
        post :create, {:bankroll => valid_attributes}, valid_session
        response.should redirect_to(Bankroll.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bankroll as @bankroll" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bankroll.any_instance.stub(:save).and_return(false)
        post :create, {:bankroll => { "purchase" => "invalid value" }}, valid_session
        assigns(:bankroll).should be_a_new(Bankroll)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bankroll.any_instance.stub(:save).and_return(false)
        post :create, {:bankroll => { "purchase" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bankroll" do
        bankroll = Bankroll.create! valid_attributes
        # Assuming there are no other bankrolls in the database, this
        # specifies that the Bankroll created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bankroll.any_instance.should_receive(:update_attributes).with({ "purchase" => "MyString" })
        put :update, {:id => bankroll.to_param, :bankroll => { "purchase" => "MyString" }}, valid_session
      end

      it "assigns the requested bankroll as @bankroll" do
        bankroll = Bankroll.create! valid_attributes
        put :update, {:id => bankroll.to_param, :bankroll => valid_attributes}, valid_session
        assigns(:bankroll).should eq(bankroll)
      end

      it "redirects to the bankroll" do
        bankroll = Bankroll.create! valid_attributes
        put :update, {:id => bankroll.to_param, :bankroll => valid_attributes}, valid_session
        response.should redirect_to(bankroll)
      end
    end

    describe "with invalid params" do
      it "assigns the bankroll as @bankroll" do
        bankroll = Bankroll.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bankroll.any_instance.stub(:save).and_return(false)
        put :update, {:id => bankroll.to_param, :bankroll => { "purchase" => "invalid value" }}, valid_session
        assigns(:bankroll).should eq(bankroll)
      end

      it "re-renders the 'edit' template" do
        bankroll = Bankroll.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bankroll.any_instance.stub(:save).and_return(false)
        put :update, {:id => bankroll.to_param, :bankroll => { "purchase" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bankroll" do
      bankroll = Bankroll.create! valid_attributes
      expect {
        delete :destroy, {:id => bankroll.to_param}, valid_session
      }.to change(Bankroll, :count).by(-1)
    end

    it "redirects to the bankrolls list" do
      bankroll = Bankroll.create! valid_attributes
      delete :destroy, {:id => bankroll.to_param}, valid_session
      response.should redirect_to(bankrolls_url)
    end
  end

end
